apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-vedtakresultat-lytter
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8099
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi