apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-vedtakresultat-lytter
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8099
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi
  kafka:
    pool: "{{ KAFKA_POOL }}"
  vault:
    enabled: true
  secureLogs:
    enabled: true
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
