/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.dp.vedtakslytter

import kotlinx.coroutines.runBlocking
import no.nav.dp.health.HealthServer

fun main(args: Array<String>) {
    runBlocking {
        val config = Configuration()
        HealthServer.startServer(config.application.httpPort).start()
    }
}

